Experimental group
394-s21/habit-tracker pull request #36
Opened 2021-04-15 22:54 UTC by tbayvas

## Trello Ticket :ticket: ##

## Summary :chart_with_upwards_trend: ##
simplified group component card
## Test plan :clipboard: ##

2021-04-15 23:15 UTC, Peiyj reviewed
Almost there! there are some empty files that you might want to remove as well.

2021-04-15 23:15 UTC, Peiyj commented on App.js
> +          name="View Group"
nit: the name should be Dashboard since it belongs to Dashboard component

2021-04-15 23:15 UTC, Peiyj commented on components/CommonCompGroupCard.js
> -import React, { Component } from 'react';
There seems to be a component exception about <Text> component in this file.

2021-04-15 23:15 UTC, Peiyj commented on screens/Dashboard.js
>                                                goal={group.goal}
Are we removing these attributes from the card component?

2021-04-15 23:15 UTC, Peiyj commented on screens/Dashboard.js
> +              {groups.map(group => <TouchableOpacity onPress={() => {this.viewGroup(group.groupID)}} value={groups.groupID}><CommonCompGroupCard
Are we still using CommonCompGroupCard or ExperimentalGroupCard?

2021-04-15 23:52 UTC, jakerogers2022 requested changes
Causes "Error: Text strings must be rendered within a <Text> component." when run on mobile

2021-04-16 21:36 UTC, jakerogers2022 approved these changes

2021-04-16 21:44 UTC, jakerogers2022 approved these changes

2021-04-16 22:27 UTC, merged